---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Project
          command: |
            # Install PHP dependencies
            composer install
      - run:
          name: Run Tests
          command: |
            # Add your test commands here
            # Example: phpunit
  deploy:
    docker:
      - image: cimg/php:7.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: >
            # Example: Deploy using SSH

            # scp -r /path/to/local/project user@your-server:/path/to/remote/project
workflows:
  version: 3
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
